# This Secret is used by pgAdmin4 to access the Postgres database
# Source: https://tfs.dspace.de/tfs/DefaultCollection/SIMPHERA/_git/nwtc?path=%2Fdeploy%2Fk8s%2Fhelm%2Fsimphera-internal%2Ftemplates%2Fpgadmin4-secret.yml
{{ if .Values.pgadmin4.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: simphera-pgadmin4-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.pgadmin4.env.password | b64enc }}

stringData:
  ## server definition
  ## https://www.pgadmin.org/docs/pgadmin4/latest/import_export_servers.html#json-format
  servers.json: |-
    {
      "Servers": {
        "1": {
          "Name": "{{ .Values.global.simphera.databases.simphera.pgHost }}",
          "Group": "Servers",
          "Port": {{ .Values.global.simphera.databases.simphera.pgPort }},
          "Username": "{{ .Values.global.simphera.databases.simphera.pgUsername }}",
          "Host": "{{ .Values.global.simphera.databases.simphera.pgHost }}",
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres"
        }
      }
    }

{{ end }}
