---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "minio") | nindent 4 }}
spec:
  ports:
  - name: minio
    port: 9000
    targetPort: 9000
  selector:
    {{- include "simphera.selectorLabels" (list . "minio") | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "minio") | nindent 4 }}
  annotations:
    {{- include "simphera.frontendIngressAnnotations" . | nindent 4 }}
spec:
{{- if .Values.global.simphera.tlsCertificates.minio }}
  tls:
  - hosts:
    - {{ .Values.global.simphera.hostnames.minio }}
    secretName: {{ .Values.global.simphera.tlsCertificates.minio }}
{{- end }}
  rules:
  - host: {{ .Values.global.simphera.hostnames.minio }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              name: minio
