apiVersion: v2
dependencies:
- name: simphera-helm-templates
  repository: file://../simphera-helm-templates
  version: '>= 0.0.0-0'
description: pgbouncer required for SIMPHERA.
name: pgbouncer
version: 23.3-2023-05-26-1639-1
