apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "keycloak") | nindent 4 }}
data:
  realmData.json: |-
{{ .Files.Get "files/realmData.json" | indent 4}}
