{{- if not .Values.global.simphera.keycloak.adminSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "keycloak") | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.global.simphera.keycloak.adminUsername | toString | b64enc }}
  password: {{ .Values.global.simphera.keycloak.adminPassword | toString | b64enc }}
{{- end -}}
