{{- if not .Values.global.simphera.minio.adminSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "minio") | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.global.simphera.minio.adminUser | toString | b64enc }}
  password: {{ .Values.global.simphera.minio.adminPassword | toString | b64enc }}
{{- end }}
