apiVersion: v2
dependencies:
- name: simphera-helm-templates
  repository: file://../simphera-helm-templates
  version: '>= 0.0.0-0'
- name: simphera
  repository: file://../simphera
  version: '>= 0.0.0-0'
- name: simphera-executoragents
  repository: file://../simphera-executoragents
  version: '>= 0.0.0-0'
- condition: global.simphera.mqtt.enabled
  name: mqtt
  repository: file://../mqtt
  version: '>= 0.0.0-0'
- condition: global.simphera.pgbouncer.enabled
  name: pgbouncer
  repository: file://../pgbouncer
  version: '>= 0.0.0-0'
- condition: global.simphera.minio.enabled
  name: minio
  repository: file://../minio
  version: '>= 0.0.0-0'
- condition: global.simphera.keycloak.enabled
  name: keycloak
  repository: file://../keycloak
  version: '>= 0.0.0-0'
description: This chart allows quickly deploying the dSPACE simphera chart with a
  minimum amount of parameters that need configuration.
name: simphera-quickstart
version: 23.3
