## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
global:
  simphera:
    image:
      registry:

      ## ref: https://kubernetes.io/docs/concepts/containers/images/#updating-images
      # IfNotPresent, Always
      pullPolicy: IfNotPresent

      ## Optionally specify an array of imagePullSecrets.
      ## Secrets must be manually created in the namespace.
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
      pullSecrets: []
      #  - myRegistryKeySecretName

    linuxNodes:
      ## Node labels for linux pod assignment
      ## https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
      nodeSelector:
        kubernetes.io/os: linux

      ## Taints to be tolerated for Pod assignment.
      ## Example:
      ##   - key: "toleration=key"
      ##     operator: "Equal"
      ##     value: "value"
      ##     effect: "NoSchedule"
      ## https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      tolerations: []

    databases:
      ## The existingSecret must contain username and password of both databases (simphera and simpheraScbtResults, if enabled)
      existingSecret: null
      simphera:
        pgDatabase:
        pgHost:
        pgPort:
        pgUsername:
        pgPassword:
        maxServerConnections: # pool_size
      simpheraScbtResults:
        enabled:
        pgDatabase:
        pgHost:
        pgPort:
        pgUsername:
        pgPassword:
        maxServerConnections: # pool_size

    clusterDomain: cluster.local

    pgbouncer:
      maxClientConnections:
      serverTlsMode: prefer

    customRootCertificates:
      existingSecret: null
      key: null

    serviceAccounts:
      simphera: null

replicas: 2

resources:
  requests:
    memory: 500Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 4
