apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "mqttmosquittobroker") | nindent 4 }}
data:
  mosquitto.conf: |-
    # Enable different settings per listener
    per_listener_settings true

    # Websocket listener on Port 9001
    listener 9001 0.0.0.0
    protocol websockets
    allow_anonymous false
    password_file /mosquitto/config/passwd.conf

    # Common options
    max_queued_messages 1000000
    persistence false
    max_inflight_messages 1
    log_type error
    log_type warning
    log_type information
    autosave_interval 300
    log_dest stdout
