apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttmosquittobroker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "mqttmosquittobroker") | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "simphera.selectorLabels" (list . "mqttmosquittobroker") | nindent 6 }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        {{- include "simphera.templateLabels" (list . "mqttmosquittobroker") | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1000
      {{- if .Values.global.simphera.serviceAccounts.simphera }}
      serviceAccountName: {{ .Values.global.simphera.serviceAccounts.simphera | quote }}
      {{- else }}
      serviceAccountName: simphera
      {{- end }}
      initContainers:
      - name: passwordconvert
        image: {{ .Values.global.simphera.image.thirdparty.mosquitto | quote }}
        imagePullPolicy: {{ .Values.global.simphera.image.pullPolicy }}
        command:
          - sh
        args:
          - '-c'
          - |
            mosquitto_passwd -b -c /mosquitto/config/passwd.conf "$MOSQUITTOUSER" "$MOSQUITTOPASSWORD"
        env:
        - name: MOSQUITTOUSER
          valueFrom:
            secretKeyRef:
              name: {{ include "simphera.mqtt.secret" . }}
              key: username
        - name: MOSQUITTOPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "simphera.mqtt.secret" . }}
              key: password
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - name: mosquitto-passwd
          mountPath: /mosquitto/config
      containers:
      - name: mqttmosquittobroker
        image: {{ .Values.global.simphera.image.thirdparty.mosquitto | quote }}
        imagePullPolicy: {{ .Values.global.simphera.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: 9001
        readinessProbe:
          tcpSocket:
            port: 9001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9001
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: mosquitto-passwd
          mountPath: /mosquitto/config/passwd.conf
          subPath: passwd.conf
        - name: mosquitto-data
          mountPath: /mosquitto/data
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        - name: mosquitto-data
          emptyDir: {}
        - name: mosquitto-passwd
          emptyDir: {}
      {{- with .Values.global.simphera.linuxNodes.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.simphera.linuxNodes.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
      {{- range .Values.global.simphera.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}

