apiVersion: v1
kind: Service
metadata:
  name: mqttmosquittobroker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "mqttmosquittobroker") | nindent 4 }}
spec:
  selector:
    {{- include "simphera.selectorLabels" (list . "mqttmosquittobroker") | nindent 4 }}
  type: ClusterIP
  ports:
  - name: mqttws
    port: 9001
    protocol: TCP
    targetPort: 9001
---
{{- if .Values.global.simphera.mqtt.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mqttmosquittobroker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "mqttmosquittobroker") | nindent 4 }}
  annotations:
    {{- include "simphera.frontendIngressAnnotations" . | nindent 4 }}
spec:
  {{- include "simphera.ingressTls" . | nindent 2 }}
  rules:
  - host: {{ .Values.global.simphera.hostnames.simphera }}
    http:
      paths:
      - path: /mqttws
        pathType: Prefix
        backend:
          service:
            name: mqttmosquittobroker
            port:
              name: mqttws
{{- end }}
