{{- $imagetag := default .Values.global.simphera.image.tag .Values.authmanager.image.tag -}}
{{- $imagetagdatamigration := default .Values.global.simphera.image.tag .Values.authmanager.datamigrationjob.image.tag -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: authmanagerservice
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "authmanagerservice") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "simphera.selectorLabels" (list . "authmanagerservice") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simphera.templateLabels" (list . "authmanagerservice") | nindent 8 }}
    spec:
      {{- include "simphera.generalPodProperties" . | nindent 6 }}
      {{- include "simphera.backendPodSecurityContextAndServiceAccount" . | nindent 6 }}
      initContainers:
      - name: authmanagerservice-init
        image: {{ .Values.global.simphera.image.registry }}/dspace/simphera/k8s-wait-for:{{ .Values.global.simphera.image.tag }}
        imagePullPolicy: {{ .Values.global.simphera.image.pullPolicy }}
        {{- include "simphera.containerSecurityContext" . | nindent 8 }}
        {{- include "simphera.initContainerResources" . | nindent 8 }}
        args:
        - "job"
        - "authmanager-migration-{{ .Release.Revision }}"
      containers:
      - name: authmanagerservice
        image: "{{ .Values.global.simphera.image.registry }}/dspace/simphera/authmanager/service:{{ $imagetag }}"
        imagePullPolicy: {{ .Values.global.simphera.image.pullPolicy }}
        {{- include "simphera.containerSecurityContext" . | nindent 8 }}
        {{- include "simphera.dotnetBusinesslogicContainerResources" . | nindent 8 }}
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 5226
          initialDelaySeconds: 3
          periodSeconds: 15
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 5226
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 5
        ports:
          - containerPort: 5226
            protocol: TCP
        env:
        {{- include "simphera.generalEnvironmentVariables" . | nindent 8 }}
        {{- include "simphera.databases.simphera.environmentVariables" . | nindent 8 }}
        volumeMounts:
        {{- include "simphera.customRootCertificates.volumeMounts" . | nindent 8 }}
      volumes:
      {{- include "simphera.customRootCertificates.volumes" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: authmanagerservice
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "authmanagerservice") | nindent 4 }}
spec:
  ports:
  - name: rest
    port: 8000
    protocol: TCP
    targetPort: 5226
  selector:
    {{- include "simphera.selectorLabels" (list . "authmanagerservice") | nindent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: authmanager-migration-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "authmanager-migration") | nindent 4 }}
  annotations:
    {{- include "simphera.migrationAnnotations" $ | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "simphera.jobTemplateLabels" (list . "authmanager-migration") | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- include "simphera.generalPodProperties" . | nindent 6 }}
      {{- include "simphera.backendPodSecurityContextAndServiceAccount" . | nindent 6 }}
      containers:
      - name: authmanager-migration
        image: "{{ .Values.global.simphera.image.registry }}/dspace/simphera/authmanager/datamigrationjob:{{ $imagetagdatamigration }}"
        imagePullPolicy: {{ .Values.global.simphera.image.pullPolicy }}
        {{- include "simphera.containerSecurityContext" . | nindent 8 }}
        {{- include "simphera.migrationContainerResources" . | nindent 8 }}
        {{- include "simphera.job.command" (list . "dotnet" "AuthManagerDataMigration.dll" "-timeToWaitDb:600") | nindent 8 }}
        env:
        {{- include "simphera.generalEnvironmentVariables" . | nindent 8 }}
        {{- include "simphera.databases.simphera.environmentVariables" . | nindent 8 }}
        volumeMounts:
        {{- include "simphera.customRootCertificates.volumeMounts" . | nindent 8 }}
      volumes:
      {{- include "simphera.customRootCertificates.volumes" . | nindent 6 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authmanagerrestapi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "authmanagerrestapi") | nindent 4 }}
  annotations:
    {{- include "simphera.restApiIngressAnnotations" . | nindent 4 }}
spec:
  {{- include "simphera.ingressTls" . | nindent 2 }}
  rules:
  - host: {{ .Values.global.simphera.hostnames.simphera }}
    http:
      paths:
      - path: /api/simphera/authentication
        pathType: Prefix
        backend:
          service:
            name: authmanagerservice
            port:
              name: rest
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authmanagerrestswagger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "authmanagerrestswagger") | nindent 4 }}
  annotations:
    {{- include "simphera.swaggerIngressAnnotations" $ | nindent 4 }}
spec:
  {{- include "simphera.ingressTls" . | nindent 2 }}
  rules:
  - host: {{ .Values.global.simphera.hostnames.simphera }}
    http:
      paths:
      - path: /api/simphera/authentication/swagger
        pathType: Prefix
        backend:
          service:
            name: authmanagerservice
            port:
              name: rest
