{{- $serviceimagetag := default .Values.global.simphera.image.tag .Values.datareplay.service.image.tag -}}
{{- $appimagetag := default .Values.global.simphera.image.tag .Values.datareplay.app.image.tag -}}
{{- $businesslogicserviceimagetag := default .Values.global.simphera.image.tag .Values.datareplay.businesslogicservice.image.tag -}}
{{- $datamigrationimagetag := default .Values.global.simphera.image.tag .Values.datareplay.datamigrationjob.image.tag -}}
{{- $restapiimagetag := default .Values.global.simphera.image.tag .Values.datareplay.restapi.image.tag -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareplay-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplay-app") | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "simphera.selectorLabels" (list . "datareplay-app") | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "simphera.templateLabels" (list . "datareplay-app") | nindent 8 }}
    spec:
      {{- include "simphera.generalPodProperties" . | nindent 6 }}
      {{- include "simphera.frontendPodSecurityContextAndServiceAccount" . | nindent 6 }}
      containers:
      - name: datareplay-app
        image: "{{ .Values.global.simphera.image.registry }}/dspace/simphera/datareplay/frontend:{{ $appimagetag }}"
        imagePullPolicy: {{ .Values.global.simphera.image.pullPolicy }}
        {{- include "simphera.frontendContainerSecurityContext" . | nindent 8 }}
        {{- include "simphera.frontendContainerResources" . | nindent 8 }}
        ports:
        - containerPort: 8080
        {{- include "simphera.frontendContainerHealthChecks" . | nindent 8 }}
        volumeMounts:
        {{- include "simphera.nginx.volumeMounts" . | nindent 8 }}
      volumes:
      {{- include "simphera.nginx.volumes" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: datareplay-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplay-app") | nindent 4 }}
spec:
  ports:
  - name: datareplay-app
    port: 3008
    targetPort: 8080
  selector:
    {{- include "simphera.selectorLabels" (list . "datareplay-app") | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datareplay-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplay-app") | nindent 4 }}
  annotations:
    {{- include "simphera.frontendIngressAnnotations" $ | nindent 4 }}
spec:
  {{- include "simphera.ingressTls" . | nindent 2 }}
  rules:
  - host: {{ .Values.global.simphera.hostnames.simphera }}
    http:
      paths:
      - path: /remoteentry/datareplay
        pathType: Prefix
        backend:
          service:
            name: datareplay-app
            port:
              name: datareplay-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareplayservice
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplayservice") | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "simphera.selectorLabels" (list . "datareplayservice") | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "simphera.templateLabels" (list . "datareplayservice") | nindent 8 }}
    spec:
      {{- include "simphera.generalPodProperties" . | nindent 6 }}
      {{- include "simphera.backendPodSecurityContextAndServiceAccount" . | nindent 6 }}
      containers:
      - name: datareplayservice
        image: "{{ .Values.global.simphera.image.registry }}/dspace/simphera/datareplay/apigateway:{{ $serviceimagetag }}"
        imagePullPolicy: {{ .Values.global.simphera.image.pullPolicy }}
        {{- include "simphera.containerSecurityContext" . | nindent 8 }}
        {{- include "simphera.dotnetBusinesslogicContainerResources" . | nindent 8 }}
        readinessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: 4008
          initialDelaySeconds: 3
          periodSeconds: 15
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /.well-known/apollo/server-health
            port: 4008
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 5
        env:
        {{- range $key, $val := .Values.env.extraEnvVars }}
        - name: {{ $key }}
          value: "{{ $val }}"
        {{- end }}
        ports:
        - containerPort: 4008
        volumeMounts:
        {{- include "simphera.customRootCertificates.volumeMounts" . | nindent 8 }}
        {{- include "simphera.serviceSettings.volumeMounts" (list . "/opt/app-root/build/servicesettings.json") | nindent 8 }}
      volumes:
      {{- include "simphera.customRootCertificates.volumes" . | nindent 6 }}
      {{- include "simphera.serviceSettings.volumes" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: datareplayservice
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplayservice") | nindent 4 }}
spec:
  ports:
  - name: drtservice
    port: 4008
    protocol: TCP
    targetPort: 4008
  selector:
    {{- include "simphera.selectorLabels" (list . "datareplayservice") | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datareplay
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplay") | nindent 4 }}
  annotations:
    {{- include "simphera.apiGatewayIngressAnnotations" . | nindent 4 }}
spec:
  {{- include "simphera.ingressTls" . | nindent 2 }}
  rules:
  - host: {{ .Values.global.simphera.hostnames.simphera }}
    http:
      paths:
      - path: /gateway/datareplay
        pathType: Prefix
        backend:
          service:
            name: datareplayservice
            port:
              name: drtservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareplaybusinesslogicservice
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplaybusinesslogicservice") | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "simphera.selectorLabels" (list . "datareplaybusinesslogicservice") | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "simphera.templateLabels" (list . "datareplaybusinesslogicservice") | nindent 8 }}
    spec:
      {{- include "simphera.generalPodProperties" . | nindent 6 }}
      {{- include "simphera.backendPodSecurityContextAndServiceAccount" . | nindent 6 }}
      initContainers:
      - name: datareplaybusinesslogicservice-init
        image: {{ .Values.global.simphera.image.registry }}/dspace/simphera/k8s-wait-for:{{ .Values.global.simphera.image.tag }}
        imagePullPolicy: {{ .Values.global.simphera.image.pullPolicy }}
        {{- include "simphera.containerSecurityContext" . | nindent 8 }}
        {{- include "simphera.initContainerResources" . | nindent 8 }}
        args:
        - "job"
        - "datareplay-migration-{{ .Release.Revision }}"
      containers:
      - name: datareplaybusinesslogicservice
        image: "{{ .Values.global.simphera.image.registry }}/dspace/simphera/datareplay/businesslogic:{{ $businesslogicserviceimagetag }}"
        imagePullPolicy: {{ .Values.global.simphera.image.pullPolicy }}
        {{- include "simphera.containerSecurityContext" . | nindent 8 }}
        {{- include "simphera.dotnetBusinesslogicContainerResources" . | nindent 8 }}
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-service=Readiness", "-addr=0.0.0.0:5008"]
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-service=Liveness", "-addr=0.0.0.0:5008"]
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 5
        env:
        {{- include "simphera.generalEnvironmentVariables" . | nindent 8 }}
        {{- include "simphera.databases.simphera.environmentVariables" . | nindent 8 }}
        {{- include "simphera.storages" . | indent 8 }}
        {{- include "simphera.customRootCertificates.environmentVariables" . | nindent 8 }}
        {{- include "simphera.recordingDataManagerSettings" . | nindent 8 }}

        # TODO: Implement one Template for feature flags adding "simphera.setFeatureFlags"
        # FORMAT:
        #     - name: FEATURE_FLAG_<NAME_OF_FEATURE>_ENABLED
        #       value: true or false
        #
        - name: FEATURE_FLAG_SHOW_KPIS_ENABLED
          value: {{ .Values.global.simphera.featureFlags.showKpis | quote }}
        - name: SCBT_SERVICE_ID
          value: "dSPACE.Simphera.DataReplayBusinessLogicService.{{ $businesslogicserviceimagetag }}"
        {{- range $key, $val := .Values.env.extraEnvVars }}
        - name: {{ $key }}
          value: "{{ $val }}"
        {{- end }}
        ports:
        - containerPort: 5008
        volumeMounts:
        {{- include "simphera.customRootCertificates.volumeMounts" . | nindent 8 }}
        {{- include "simphera.serviceSettings.volumeMounts" (list . "/usr/app/servicesettings.json") | nindent 8 }}
      volumes:
      {{- include "simphera.customRootCertificates.volumes" . | nindent 6 }}
      {{- include "simphera.serviceSettings.volumes" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: datareplaybusinesslogicservice
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplaybusinesslogicservice") | nindent 4 }}
spec:
  ports:
  - name: grpc
    port: 5008
    protocol: TCP
    targetPort: 5008
  selector:
    {{- include "simphera.selectorLabels" (list . "datareplaybusinesslogicservice") | nindent 4 }}
---
apiVersion: batch/v1 # Migration Job
kind: Job
metadata:
  name: datareplay-migration-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplay-migration") | nindent 4 }}
  annotations:
    {{- include "simphera.migrationAnnotations" $ | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "simphera.jobTemplateLabels" (list . "datareplay-migration") | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- include "simphera.generalPodProperties" . | nindent 6 }}
      {{- include "simphera.backendPodSecurityContextAndServiceAccount" . | nindent 6 }}
      containers:
      - name: datareplay-migration
        image: "{{ .Values.global.simphera.image.registry }}/dspace/simphera/datareplay/datamigrationjob:{{ $datamigrationimagetag }}"
        imagePullPolicy: {{ .Values.global.simphera.image.pullPolicy }}
        {{- include "simphera.containerSecurityContext" . | nindent 8 }}
        {{- include "simphera.migrationContainerResources" . | nindent 8 }}
        {{- include "simphera.job.command" (list . "dotnet" "DataReplayDataMigrationJob.dll") | nindent 8 }}
        env:
        {{- include "simphera.generalEnvironmentVariables" . | nindent 8 }}
        {{- include "simphera.databases.simphera.environmentVariables" . | nindent 8 }}
        - name: SCBT_SERVICE_ID
          value: "dSPACE.Simphera.Server.DataReplay.DataMigrationJob.{{ $datamigrationimagetag }}"
        {{- range $key, $val := .Values.env.extraEnvVars }}
        - name: {{ $key }}
          value: "{{ $val }}"
        {{- end }}
        volumeMounts:
        {{- include "simphera.customRootCertificates.volumeMounts" . | nindent 8 }}
      volumes:
      {{- include "simphera.customRootCertificates.volumes" . | nindent 6 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datareplayrestapi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplayrestapi") | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "simphera.selectorLabels" (list . "datareplayrestapi") | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "simphera.templateLabels" (list . "datareplayrestapi") | nindent 8 }}
    spec:
      {{- include "simphera.generalPodProperties" . | nindent 6 }}
      {{- include "simphera.backendPodSecurityContextAndServiceAccount" . | nindent 6 }}
      containers:
      - name: datareplayrestapi
        image: "{{ .Values.global.simphera.image.registry }}/dspace/simphera/datareplay/api:{{ $restapiimagetag }}"
        imagePullPolicy: {{ .Values.global.simphera.image.pullPolicy }}
        {{- include "simphera.containerSecurityContext" . | nindent 8 }}
        {{- include "simphera.restApiContainerResources" . | nindent 8 }}
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 6008
          initialDelaySeconds: 3
          periodSeconds: 15
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 6008
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 5
        ports:
        - containerPort: 6008
        env:
        {{- include "simphera.generalEnvironmentVariables" . | nindent 8 }}
        {{- include "simphera.customRootCertificates.environmentVariables" . | nindent 8 }}
        - name: SCBT_SERVICE_ID
          value: "dSPACE.Simphera.Server.DataReplay.RestApi.{{ $restapiimagetag }}"
        - name: ROUTE_PREFIX
          value: api/simphera/data-replay-testing
        {{- range $key, $val := .Values.env.extraEnvVars }}
        - name: {{ $key }}
          value: "{{ $val }}"
        {{- end }}
        volumeMounts:
        {{- include "simphera.customRootCertificates.volumeMounts" . | nindent 8 }}
        {{- include "simphera.serviceSettings.volumeMounts" (list . "/usr/app/servicesettings.json") | nindent 8 }}
      volumes:
      {{- include "simphera.customRootCertificates.volumes" . | nindent 6 }}
      {{- include "simphera.serviceSettings.volumes" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: datareplayrestapi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplayrestapi") | nindent 4 }}
spec:
  ports:
  - name: datareplayapi
    port: 6008
    protocol: TCP
    targetPort: 6008
  selector:
    {{- include "simphera.selectorLabels" (list . "datareplayrestapi") | nindent 4 }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datareplayrestapi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplayrestapi") | nindent 4 }}
  annotations:
    {{- include "simphera.restApiIngressAnnotations" . | nindent 4 }}
spec:
  {{- include "simphera.ingressTls" . | nindent 2 }}
  rules:
  - host: {{ .Values.global.simphera.hostnames.simphera }}
    http:
      paths:
      - path: /api/simphera/data-replay-testing
        pathType: Prefix
        backend:
          service:
            name: datareplayrestapi
            port:
              name: datareplayapi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datareplayrestswagger
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "datareplayrestswagger") | nindent 4 }}
  annotations:
    {{- include "simphera.swaggerIngressAnnotations" $ | nindent 4 }}
spec:
  {{- include "simphera.ingressTls" . | nindent 2 }}
  rules:
  - host: {{ .Values.global.simphera.hostnames.simphera }}
    http:
      paths:
      - path: /api/simphera/data-replay-testing/swagger
        pathType: Prefix
        backend:
          service:
            name: datareplayrestapi
            port:
              name: datareplayapi
