{{- if not .Values.global.simphera.databases.simphera.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: database-simphera-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.global.simphera.databases.simphera.pgUsername | toString | b64enc }}
  password: {{ .Values.global.simphera.databases.simphera.pgPassword | toString | b64enc }}
---
{{- end }}
{{- if not .Values.global.simphera.databases.simpheraScbtResults.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: database-simphera-scbt-results-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.global.simphera.databases.simpheraScbtResults.pgUsername | toString | b64enc }}
  password: {{ .Values.global.simphera.databases.simpheraScbtResults.pgPassword | toString | b64enc }}
---
{{- end }}
