{{- $imagetag := default .Values.global.simphera.image.tag .Values.help.image.tag -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: help
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "help") | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "simphera.selectorLabels" (list . "help") | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "simphera.templateLabels" (list . "help") | nindent 8 }}
    spec:
      {{- include "simphera.generalPodProperties" . | nindent 6 }}
      {{- include "simphera.frontendPodSecurityContextAndServiceAccount" . | nindent 6 }}
      containers:
      - name: help
        image: "{{ .Values.global.simphera.image.registry }}/dspace/simphera/core/docs/help:{{ $imagetag }}"
        imagePullPolicy: {{ .Values.global.simphera.image.pullPolicy }}
        {{- include "simphera.frontendContainerSecurityContext" . | nindent 8 }}
        {{- include "simphera.frontendContainerResources" . | nindent 8 }}
        ports:
        - containerPort: 8080
        {{- include "simphera.frontendContainerHealthChecks" . | nindent 8 }}
        volumeMounts:
        {{- include "simphera.nginx.volumeMounts" . | nindent 8 }}
      volumes:
      {{- include "simphera.nginx.volumes" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: help
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "help") | nindent 4 }}
spec:
  ports:
  - name: help
    port: 3050
    targetPort: 8080
  selector:
    {{- include "simphera.selectorLabels" (list . "help") | nindent 4 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: help
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "help") | nindent 4 }}
  annotations:
    {{- include "simphera.frontendIngressAnnotations" $ | nindent 4 }}
spec:
  {{- include "simphera.ingressTls" . | nindent 2 }}
  rules:
  - host: {{ .Values.global.simphera.hostnames.simphera }}
    http:
      paths:
      - path: /help
        pathType: Prefix
        backend:
          service:
            name: help
            port:
              name: help
