{{- if not .Values.global.simphera.serviceAccounts.simphera }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simphera
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "simphera") | nindent 4 }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simphera
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "simphera") | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods/log", "pods"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simphera
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simphera.resourceLabels" (list . "simphera") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simphera
subjects:
  - kind: ServiceAccount
    {{- if .Values.global.simphera.serviceAccounts.simphera }}
    name: {{ .Values.global.simphera.serviceAccounts.simphera | quote }}
    {{- else }}
    name: simphera
    {{- end }}
    namespace: {{ .Release.Namespace }}
